name: PixArt
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=2.7.0
  - torchvision=0.22.0
  - torchaudio=2.0.2
  - pytorch-cuda=11.7
  - pip:
    - timm==0.6.12
    - diffusers
    - accelerate
    - mmcv==1.7.0
    - tensorboard
    - transformers>=4.30.0
    - sentencepiece~=0.1.97
    - ftfy~=6.1.1
    - beautifulsoup4~=4.11.1
    - opencv-python
    - bs4
    - einops
    - xformers
    - torchmetrics==1.7.1
    - bitsandbytes