name: DiT
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12.9
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=11.8
  - scipy=1.15.2
  - pip
  - pip:
    - timm
    - diffusers
    - accelerate